### ISSUE TITLE
Tracker not tracking correctly

### ISSUE THREAD

**Issue by KobraBytes** [Razviar/marvelsnaptracker#15]
Hi,

Im really not sure how reliable this tracker is. I have just synced for the first time and I noticed that "Super Skrull" it says is not owned. Yet on my phone/tablet etc i do own him. Im not sure how many more are wrong but if 1 is wrong its hard to rely on its integrity. Please can you resolve.

thanks

KB

**Comment by Razviar** [comment]
It updates ONLY when you play on PC. So maybe you recieved this card on mobile version and haven't synced yet on PC client. I didn't notice any inaccuracies in collection regards till now. You can check by yourself:
go to C:\Users\{YOUR_USERNAME}\AppData\LocalLow\Second Dinner\SNAP\Standalone\States\nvprod and find CollectionState.json file there. Then open it and serach for SuperSkrull.

Also, tracker updates info on site with a little delay due to caching. So it might be in the database but not updated in frontend yet. Please let me know your user name so I could verufy.

**Comment by KobraBytes** [comment]
Sorry my bad i didnt realize it only syncs from PC. I ran it from PC and tested it there and it works perfectly! Thank you for you efforts and quick reply!
